package pro.erez.interstice.test;

import com.google.gson.*;
import com.mojang.brigadier.arguments.*;
import java.net.InetSocketAddress;
import java.nio.file.*;
import java.util.*;
import net.minecraft.commands.Commands;
import net.minecraft.core.*;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.Registries;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.*;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.storage.LevelResource;
import net.minecraft.world.phys.AABB;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.RegisterCommandsEvent;
import net.neoforged.neoforge.event.entity.player.PlayerEvent;
import net.neoforged.neoforge.event.server.ServerStartedEvent;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import pro.erez.interstice.Interstice;
import pro.erez.interstice.expedition.ExpeditionLedger;
import pro.erez.interstice.fauna.CanopySentinel;
import pro.erez.interstice.gear.RouteBeaconEntity;
import pro.erez.interstice.lift.*;
import pro.erez.interstice.rift.*;
import pro.erez.interstice.smoke.net.V6NetworkFiles;

/** A fresh dedicated JVM loads the first run's exact world. It never recreates its fixtures. */
@EventBusSubscriber(modid=Interstice.ID)
public final class V6DedicatedColdRestart {
    private static final boolean ENABLED=Boolean.getBoolean("interstice.v6NetworkColdRestart");
    private static final String SESSION=UUID.randomUUID().toString();
    private static final String[] PHASES={"cold_world_identity","cold_loaded_saved_objects","cold_real_two_client_login","cold_native_synced_cargo_and_entities","cold_final_receipts"};
    private static MinecraftServer server;
    private static JsonObject baseline,previous,result=new JsonObject(),instructions=new JsonObject();
    private static final JsonArray phases=new JsonArray(),events=new JsonArray();
    private static final UUID[] uuids=new UUID[3];
    private static final long[] pids=new long[3];
    private static final boolean[] acks=new boolean[3],receipts=new boolean[3];
    private static BlockPos anchorPos,beaconPos,guardianFeet,home;
    private static UUID liftUuid,guardianUuid;
    private static int tick,phase,token,phaseBegan;
    private static boolean started,finished,failed,terminalValidated;
    private static V6DedicatedScenario.Quiescence quiescence;

    @SubscribeEvent public static void commands(RegisterCommandsEvent event){if(!ENABLED)return;
        event.getDispatcher().register(Commands.literal("v6net").requires(s->s.getEntity() instanceof ServerPlayer p&&peer(p)>0)
            .then(Commands.literal("hello").then(Commands.argument("pid",LongArgumentType.longArg(1)).executes(c->{var p=c.getSource().getPlayerOrException();int id=peer(p);long supplied=LongArgumentType.getLong(c,"pid");require(pids[id]==0||pids[id]==supplied,"Cold peer changed its physical PID");require(supplied!=baseline.getAsJsonObject("peers").getAsJsonObject(Integer.toString(id)).get("previous_pid").getAsLong(),"Cold peer must use a new JVM PID");require(p.connection.getConnection().getRemoteAddress() instanceof InetSocketAddress a&&a.getAddress().isLoopbackAddress(),"Cold peer must use real loopback TCP");pids[id]=supplied;record("actual_hello",p);return 1;})))
            .then(Commands.literal("ack").then(Commands.argument("token",IntegerArgumentType.integer(0)).executes(c->{if(IntegerArgumentType.getInteger(c,"token")!=token)return 0;acks[peer(c.getSource().getPlayerOrException())]=true;return 1;})))
            .then(Commands.literal("receipt").then(Commands.argument("token",IntegerArgumentType.integer(0)).executes(c->{require(finished&&IntegerArgumentType.getInteger(c,"token")==token,"Cold receipt must use current final token");receipts[peer(c.getSource().getPlayerOrException())]=true;return 1;}))));
    }
    @SubscribeEvent public static void start(ServerStartedEvent event){if(!ENABLED)return;server=event.getServer();try{
        V6NetworkFiles.validate();require(!Boolean.getBoolean("interstice.v6NetworkScenario"),"Live and cold scenarios are mutually exclusive");
        require(server.isDedicatedServer()&&server.getPort()==V6NetworkFiles.PORT&&!server.isFlightAllowed(),"Cold requires dedicated port26593 and allow-flight=false");
        Path input=Path.of(System.getProperty("interstice.v6NetworkColdInput",""));require(input.isAbsolute()&&input.toString().replace('\\','/').contains("/.verification/")&&Files.isRegularFile(input),"Cold input must be an explicit existing isolated cold-baseline.json");
        require(!input.getParent().toRealPath().equals(V6NetworkFiles.EVIDENCE.toRealPath()),"Cold evidence must be separate from its immutable first-run input");
        baseline=JsonParser.parseString(Files.readString(input)).getAsJsonObject();previous=JsonParser.parseString(Files.readString(input.resolveSibling("v6-network-server.json"))).getAsJsonObject();
        require(baseline.get("eligible").getAsBoolean()&&previous.get("passed").getAsBoolean()&&previous.get("finished").getAsBoolean()&&previous.get("generation_quiescent_before_halt").getAsBoolean(),"Cold requires a fully passed and normally quiesced first server run");
        require(baseline.get("session_id").getAsString().equals(previous.get("session_id").getAsString()),"Cold input/report session mismatch");
        require(ProcessHandle.current().pid()!=baseline.get("previous_server_pid").getAsLong(),"Cold server must have a new physical JVM PID");
        require(server.getServerDirectory().toRealPath().toString().equals(baseline.get("server_directory").getAsString())&&server.getWorldPath(LevelResource.ROOT).toRealPath().toString().equals(baseline.get("world_directory").getAsString()),"Cold must reopen the exact first dedicated server/world directory");
        require(server.overworld().getSeed()==baseline.get("world_seed").getAsLong(),"Cold actual world seed changed");
        require(baseline.has("guardian"),"First-run persisted guardian proof is required, no substitute is spawned");
        anchorPos=V6NetworkFiles.point(baseline.getAsJsonObject("lift").getAsJsonObject("anchor_pos"));beaconPos=V6NetworkFiles.point(baseline.getAsJsonObject("beacon").getAsJsonObject("pos"));guardianFeet=V6NetworkFiles.point(baseline.getAsJsonObject("guardian").getAsJsonObject("feet"));home=V6NetworkFiles.point(baseline.getAsJsonObject("guardian").getAsJsonObject("home"));liftUuid=UUID.fromString(baseline.getAsJsonObject("lift").get("lift_uuid").getAsString());guardianUuid=UUID.fromString(baseline.getAsJsonObject("guardian").get("uuid").getAsString());
        result.addProperty("session_id",SESSION);result.addProperty("previous_session_id",baseline.get("session_id").getAsString());result.addProperty("server_pid",ProcessHandle.current().pid());result.addProperty("previous_server_pid",baseline.get("previous_server_pid").getAsLong());result.addProperty("cold_input",input.toRealPath().toString());result.addProperty("cold_input_sha256",java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(input))));result.addProperty("server_directory",server.getServerDirectory().toRealPath().toString());result.addProperty("world_directory",server.getWorldPath(LevelResource.ROOT).toRealPath().toString());result.addProperty("world_seed",server.overworld().getSeed());result.addProperty("dedicated_server",true);result.addProperty("allow_flight",server.isFlightAllowed());result.addProperty("scope","Actual second JVM reopen of the same world, saved identities/cargo/journeys and native client menu/entity synchronization; no fixture placement, spawn, fuel injection or synthetic reload");result.add("phases",phases);result.add("events",events);started=true;pass("Actual new dedicated PID reopened the exact saved world/seed after first-run quiescence");setPhase(1);loadWindow();write();
    }catch(Throwable failure){fail(failure);}}
    @SubscribeEvent public static void login(PlayerEvent.PlayerLoggedInEvent event){if(!ENABLED||!(event.getEntity() instanceof ServerPlayer p)||peer(p)==0)return;try{int id=peer(p);require(baseline!=null&&p.getUUID().toString().equals(baseline.getAsJsonObject("peers").getAsJsonObject(Integer.toString(id)).get("uuid").getAsString()),"Cold actual player UUID differs from first run");uuids[id]=p.getUUID();record("actual_login",p);}catch(Throwable failure){fail(failure);}}
    @SubscribeEvent public static void logout(PlayerEvent.PlayerLoggedOutEvent event){if(ENABLED&&event.getEntity() instanceof ServerPlayer p&&peer(p)>0)record("actual_logout",p);}
    @SubscribeEvent public static void tick(ServerTickEvent.Post event){if(!ENABLED||server!=event.getServer()||(!started&&!finished))return;tick++;try{
        if(!finished&&Files.isRegularFile(V6NetworkFiles.EVIDENCE.resolve("runner-request.json"))){var request=V6NetworkFiles.read("runner-request.json");if(request.get("session_id").getAsString().equals(SESSION))throw new IllegalStateException("Own runner requested cooperative cold stop");}
        if(finished){quiescence.tick(server);if(tick%20==0)write();if(quiescence.ready()&&terminalPeers()){if(!terminalValidated){terminalValidated=true;pass("Final real-client receipts/clean disconnect and generation quiescence");}result.addProperty("generation_quiescent_before_halt",true);result.add("quiescence",quiescence.json());write();server.halt(false);}return;}
        if(tick%200==0)System.out.println("V6_NETWORK_COLD_PROGRESS phase="+PHASES[phase]+" age="+(tick-phaseBegan));
        require(server.getPlayerList().getPlayers().stream().allMatch(p->peer(p)>0),"Cold isolated server found an unrelated player");require(tick-phaseBegan<6000,"Cold phase deadline "+PHASES[phase]);
        if(phase==1&&tick-phaseBegan>20&&server.overworld().getEntity(liftUuid) instanceof FieldLiftEntity&&server.overworld().getEntity(guardianUuid) instanceof CanopySentinel){checkSaved();pass("Loaded actual persisted lift/26 cargo/beacon/guardian/portal and spent server entitlement");setPhase(2);}
        else if(phase==2&&player(1)!=null&&player(2)!=null&&pids[1]>0&&pids[2]>0){require(pids[1]!=pids[2]&&pids[1]!=ProcessHandle.current().pid()&&pids[2]!=ProcessHandle.current().pid(),"Cold requires three distinct physical JVMs");checkJourneys();pass("Two actual new TCP clients logged in with the same saved player/journey UUIDs");setPhase(3);var lift=(FieldLiftEntity)server.overworld().getEntity(liftUuid);var one=action("cold_lift_menu");one.addProperty("lift_id",lift.getId());one.addProperty("lift_uuid",lift.getUUID().toString());instructions.add("1",one);var guardian=(CanopySentinel)server.overworld().getEntity(guardianUuid);var two=action("cold_observe");two.add("beacon_pos",V6NetworkFiles.point(beaconPos));two.addProperty("beacon_uuid",baseline.getAsJsonObject("beacon").get("marker_uuid").getAsString());two.addProperty("guardian_id",guardian.getId());two.addProperty("guardian_uuid",guardian.getUUID().toString());instructions.add("2",two);write();}
        else if(phase==3){require(player(1)!=null&&player(2)!=null,"Cold client unexpectedly disconnected");if(acks[1]&&acks[2]){var one=V6NetworkFiles.read("peer-1.json");var two=V6NetworkFiles.read("peer-2.json");if(one.has("cold_native_menu_stone_count")&&two.has("cold_actual_guardian_uuid")){require(one.get("cold_native_menu_stone_count").getAsInt()==26&&one.get("cold_native_menu_lift_uuid").getAsString().equals(liftUuid.toString())&&two.get("cold_actual_guardian_uuid").getAsString().equals(guardianUuid.toString())&&two.get("cold_actual_beacon_uuid").getAsString().equals(baseline.getAsJsonObject("beacon").get("marker_uuid").getAsString()),"Cold native client evidence disagrees with actual persisted objects");checkSaved();pass("Ordinary reopened cargo menu received26 stones; second real client received saved beacon/guardian UUIDs");result.addProperty("cold_server_restart_checked",true);finish();}}}
        if(tick%20==0)write();
    }catch(Throwable failure){fail(failure);}}
    private static void loadWindow(){for(var point:List.of(anchorPos,beaconPos,guardianFeet,home)){for(int dx=-1;dx<=1;dx++)for(int dz=-1;dz<=1;dz++)server.overworld().getChunk((point.getX()>>4)+dx,(point.getZ()>>4)+dz);}var portal=baseline.getAsJsonObject("portal");for(String key:List.of("source","echo")){var dimension=ResourceKey.create(Registries.DIMENSION,ResourceLocation.parse(portal.get(key+"_dimension").getAsString()));var level=server.getLevel(dimension);require(level!=null,"Cold saved portal dimension is missing");var point=V6NetworkFiles.point(portal.getAsJsonObject(key));for(int dx=-1;dx<=1;dx++)for(int dz=-1;dz<=1;dz++)level.getChunk((point.getX()>>4)+dx,(point.getZ()>>4)+dz);}}
    private static void checkSaved(){var saved=baseline.getAsJsonObject("lift");require(server.overworld().getBlockEntity(anchorPos) instanceof FieldAnchorEntity,"Cold saved anchor block entity missing");var anchor=(FieldAnchorEntity)server.overworld().getBlockEntity(anchorPos);var lift=anchor.lift();require(lift!=null&&lift.getUUID().equals(liftUuid)&&anchor.anchorId().toString().equals(saved.get("anchor_uuid").getAsString())&&anchor.owner().toString().equals(saved.get("owner_uuid").getAsString())&&anchor.fuel()==saved.get("fuel").getAsInt()&&!anchor.commanded()&&anchor.status()==FieldAnchorEntity.Status.STOPPED&&Math.abs(lift.getY()-saved.get("y").getAsDouble())<.0001,"Cold anchor/lift identity/state/fuel changed");require(lift.cargo().countItem(Items.STONE)==26&&lift.quarantinedCargoRecords()==0,"Cold cargo lost/duplicated/quarantined stones");var cargo=new JsonArray();for(int slot=0;slot<27;slot++){var stack=lift.cargo().getItem(slot);if(!stack.isEmpty()){var item=new JsonObject();item.addProperty("slot",slot);item.addProperty("id",BuiltInRegistries.ITEM.getKey(stack.getItem()).toString());item.addProperty("count",stack.getCount());cargo.add(item);}}require(cargo.equals(saved.getAsJsonArray("cargo")),"Cold cargo slot inventory changed");require(server.overworld().getEntitiesOfClass(FieldLiftEntity.class,new AABB(anchorPos).inflate(4,64,4)).stream().filter(e->e.anchorPos().equals(anchorPos)).count()==1,"Cold loaded window contains duplicate world-owned lift");
        var beaconSaved=baseline.getAsJsonObject("beacon");require(server.overworld().getBlockEntity(beaconPos) instanceof RouteBeaconEntity,"Cold beacon block entity missing");var beacon=(RouteBeaconEntity)server.overworld().getBlockEntity(beaconPos);require(beacon.markerId().toString().equals(beaconSaved.get("marker_uuid").getAsString())&&beacon.owner().toString().equals(beaconSaved.get("owner_uuid").getAsString())&&beacon.markerName().equals(beaconSaved.get("name").getAsString())&&beacon.fuelTicks()>=Math.max(0,beaconSaved.get("fuel_ticks").getAsInt()-(previous.get("server_tick").getAsInt()-baseline.get("server_tick").getAsInt()+tick+5))&&beacon.fuelTicks()<=beaconSaved.get("fuel_ticks").getAsInt(),"Cold saved beacon identity/name or bounded naturally consumed fuel changed");
        require(server.overworld().getEntity(guardianUuid) instanceof CanopySentinel,"Cold guardian entity missing");var guardian=(CanopySentinel)server.overworld().getEntity(guardianUuid);var guardianSaved=baseline.getAsJsonObject("guardian");require(guardian.home().equals(home)&&guardian.isCanopyResident()==guardianSaved.get("canopy_resident").getAsBoolean(),"Cold guardian UUID/home/residency changed");require(guardian.warningTicksRemaining()>=0&&guardian.warningTicksRemaining()<=CanopySentinel.WARNING_TICKS&&guardian.cooldownTicksRemaining()>=0&&guardian.cooldownTicksRemaining()<=CanopySentinel.COOLDOWN_TICKS,"Cold guardian timers outside their real runtime bounds");
        var portal=baseline.getAsJsonObject("portal");var links=RiftLinks.get(server);var link=links.byId(UUID.fromString(portal.get("uuid").getAsString()));require(link!=null&&link.kind()==RiftLinks.Kind.PORTAL&&links.size()==portal.get("saved_link_count").getAsInt()&&link.source().pos().equals(V6NetworkFiles.point(portal.getAsJsonObject("source")))&&link.echo().pos().equals(V6NetworkFiles.point(portal.getAsJsonObject("echo")))&&link.source().dimension().location().toString().equals(portal.get("source_dimension").getAsString())&&link.echo().dimension().location().toString().equals(portal.get("echo_dimension").getAsString())&&link.source().axis().getName().equals(portal.get("source_axis").getAsString())&&link.echo().axis().getName().equals(portal.get("echo_axis").getAsString()),"Cold saved portal UUID/endpoints changed");require(RiftGeometry.valid(server.getLevel(link.source().dimension()),new RiftGeometry.Frame(link.source().pos(),link.source().axis()),true)&&server.getLevel(link.echo().dimension()).getBlockState(link.echo().pos()).is(Interstice.RIFT_ECHO.get()),"Cold physical portal/echo failed to persist");checkJourneys();
        var proof=new JsonObject();proof.addProperty("lift_uuid",lift.getUUID().toString());proof.addProperty("cargo_stones",lift.cargo().countItem(Items.STONE));proof.addProperty("beacon_uuid",beacon.markerId().toString());proof.addProperty("beacon_fuel_actual",beacon.fuelTicks());proof.addProperty("guardian_uuid",guardian.getUUID().toString());proof.add("guardian_home",V6NetworkFiles.point(guardian.home()));proof.addProperty("guardian_phase_actual",guardian.phase().name());proof.addProperty("guardian_warning_actual",guardian.warningTicksRemaining());proof.addProperty("guardian_cooldown_actual",guardian.cooldownTicksRemaining());proof.addProperty("guardian_timer_scope","Natural running AI timers are reported, not claimed equal to a pre-save observation");proof.addProperty("portal_uuid",link.id().toString());proof.addProperty("fixture_recreation",false);result.add("persisted_objects",proof);
    }
    private static void checkJourneys(){var proof=new JsonObject();for(int id=1;id<=2;id++){var expected=baseline.getAsJsonObject("peers").getAsJsonObject(Integer.toString(id));var uuid=UUID.fromString(expected.get("uuid").getAsString());var journey=ExpeditionLedger.get(server).journey(uuid);require(journey!=null&&journey.id().toString().equals(expected.get("journey_uuid").getAsString())&&journey.entered()==expected.get("entered").getAsBoolean()&&journey.spent()==expected.get("spent").getAsBoolean()&&journey.origin().dimension().location().toString().equals(expected.get("origin_dimension").getAsString())&&journey.origin().feet().equals(V6NetworkFiles.point(expected.getAsJsonObject("origin_feet"))),"Cold server-owned journey identity/entitlement changed");if(id==2)require(journey.spent(),"Cold second player's emergency entitlement must remain spent");var row=new JsonObject();row.addProperty("player_uuid",uuid.toString());row.addProperty("journey_uuid",journey.id().toString());row.addProperty("spent",journey.spent());proof.add(Integer.toString(id),row);}result.add("saved_journeys",proof);}
    private static void setPhase(int next){phase=next;token++;phaseBegan=tick;Arrays.fill(acks,false);instructions=new JsonObject();for(int id=1;id<=2;id++)instructions.add(Integer.toString(id),action("wait"));System.out.println("V6_NETWORK_COLD_PHASE phase="+PHASES[phase]+" token="+token);}
    private static JsonObject action(String value){var row=new JsonObject();row.addProperty("action",value);return row;}
    private static int peer(ServerPlayer p){return V6NetworkFiles.id(p.getGameProfile().getName());}
    private static ServerPlayer player(int id){return uuids[id]==null?null:server.getPlayerList().getPlayer(uuids[id]);}
    private static void record(String kind,ServerPlayer p){var row=new JsonObject();row.addProperty("kind",kind);row.addProperty("peer",peer(p));row.addProperty("uuid",p.getUUID().toString());row.addProperty("server_tick",tick);row.addProperty("remote_address",String.valueOf(p.connection.getConnection().getRemoteAddress()));events.add(row);}
    private static void pass(String detail){var row=new JsonObject();row.addProperty("phase",PHASES[phase]);row.addProperty("status","passed");row.addProperty("actual_server_ticks",tick-phaseBegan);row.addProperty("detail",detail);phases.add(row);}
    private static void write(){try{var state=new JsonObject();state.addProperty("session_id",SESSION);state.addProperty("server_pid",ProcessHandle.current().pid());state.addProperty("server_ready",started);state.addProperty("token",token);state.addProperty("phase",PHASES[phase]);state.addProperty("server_tick",tick);state.addProperty("finished",finished);state.addProperty("cold_restart",true);state.addProperty("passed",finished&&!failed);state.addProperty("phase_checks_passed",finished&&!failed);state.addProperty("minimum_network_passed",false);state.add("peers",instructions);V6NetworkFiles.write("state.json",state);result.addProperty("finished",finished);result.addProperty("passed",finished&&terminalValidated&&!failed);result.addProperty("phase_checks_passed",finished&&!failed);result.addProperty("phase",PHASES[phase]);result.addProperty("server_tick",tick);var actual=new JsonObject();for(int id=1;id<=2;id++){var row=new JsonObject();row.addProperty("client_pid",pids[id]);var p=player(id);row.addProperty("connected",p!=null&&p.connection.getConnection().isConnected());if(p!=null){row.addProperty("uuid",p.getUUID().toString());row.addProperty("dimension",p.level().dimension().location().toString());row.addProperty("mayfly",p.getAbilities().mayfly);row.addProperty("flying",p.getAbilities().flying);}actual.add(Integer.toString(id),row);}result.add("actual_peers",actual);V6NetworkFiles.write("v6-network-cold-server.json",result);}catch(Throwable error){error.printStackTrace();}}
    private static void fail(Throwable error){error.printStackTrace();failed=true;result.addProperty("error",error.toString());var row=new JsonObject();row.addProperty("phase",PHASES[phase]);row.addProperty("status","failed");row.addProperty("detail",error.toString());phases.add(row);finish();}
    private static void finish(){finished=true;setPhase(4);for(int id=1;id<=2;id++)instructions.add(Integer.toString(id),action("finish"));quiescence=new V6DedicatedScenario.Quiescence();write();}
    private static boolean terminalPeers(){for(int id=1;id<=2;id++){if(receipts[id])continue;try{var peer=V6NetworkFiles.read("peer-"+id+".json");if(peer.has("own_client_clean_disconnect")&&peer.get("own_client_clean_disconnect").getAsBoolean()&&peer.get("session_id").getAsString().equals(SESSION))continue;}catch(Exception absent){}return false;}return true;}
    private static void require(boolean value,String message){if(!value)throw new IllegalStateException(message);}
    private V6DedicatedColdRestart(){}
}
