modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="interstice"
version="${version}"
displayName="Interstice: Toxic Seas Prototype"
description='''Light and heavy toxic fluids flowing in opposite directions.'''

[[dependencies.interstice]]
modId="neoforge"
type="required"
versionRange="[21.1.252,)"
ordering="NONE"
side="BOTH"

[[dependencies.interstice]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="interstice.mixins.json"
