modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0"

[[mods]]
modId="interstice"
version="${version}"
displayName="Interstice: Toxic Realm"
description='''An alien realm between toxic seas: unusual terrain, tides, dangerous flora and cave spiders, mineral processing and expedition equipment. V6 geography is available as a preview.'''

[[dependencies.interstice]]
modId="neoforge"
type="required"
versionRange="[21.1.252,)"
ordering="NONE"
side="BOTH"

[[dependencies.interstice]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="interstice.mixins.json"
