package pro.erez.interstice;

import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.RandomSource;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.SnowLayerBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.lighting.LightEngine;
import net.minecraft.world.level.material.MapColor;

/**
 * Surface covering block for Interstice islands — dark riftstone underneath,
 * topped with faintly luminous ash-mauve growth. Replaces the vanilla grass/dirt surface
 * generated by noise surface rules.
 *
 * Emits a faint glow (light level 2) to simulate bioluminescence.
 */
public final class AbyssalTurfBlock extends Block {
    public AbyssalTurfBlock() {
        super(BlockBehaviour.Properties.of()
                .mapColor(MapColor.COLOR_PURPLE)
                .strength(0.8F, 2.0F)
                .sound(SoundType.MOSS)
                .lightLevel(s -> 2)
                .randomTicks()
                .requiresCorrectToolForDrops());
    }

    /** Vanilla surface-occlusion rules, without the sunlight requirement of terrestrial grass. */
    public static boolean canKeepCover(BlockState state, BlockGetter level, BlockPos pos) {
        BlockPos abovePos = pos.above();
        BlockState above = level.getBlockState(abovePos);
        if (above.is(Blocks.SNOW) && above.getValue(SnowLayerBlock.LAYERS) == 1) return true;
        if (above.getFluidState().getAmount() == 8) return false;
        int blocked = LightEngine.getLightBlockInto(level, state, pos, above, abovePos,
                Direction.UP, above.getLightBlock(level, abovePos));
        return blocked < 15;
    }
    private void checkCover(BlockState state, ServerLevel level, BlockPos pos) {
        if (!canKeepCover(state, level, pos)) level.setBlockAndUpdate(pos, Interstice.RIFTSTONE.get().defaultBlockState());
    }
    @Override public void onPlace(BlockState state, Level level, BlockPos pos, BlockState old, boolean moved) {
        super.onPlace(state, level, pos, old, moved);
        if (!level.isClientSide) level.scheduleTick(pos, this, 20);
    }
    @Override public BlockState updateShape(BlockState state, Direction direction, BlockState neighbor,
            LevelAccessor level, BlockPos pos, BlockPos neighborPos) {
        if (direction == Direction.UP) level.scheduleTick(pos, this, 20);
        return super.updateShape(state, direction, neighbor, level, pos, neighborPos);
    }
    @Override public void tick(BlockState state, ServerLevel level, BlockPos pos, RandomSource random) { checkCover(state, level, pos); }
    @Override public void randomTick(BlockState state, ServerLevel level, BlockPos pos, RandomSource random) { checkCover(state, level, pos); }
}
