package pro.erez.interstice;

import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;

/**
 * Surface covering block for Interstice islands — dark riftstone underneath,
 * topped with bioluminescent teal moss. Replaces the vanilla grass/dirt surface
 * generated by noise surface rules.
 *
 * Emits a faint glow (light level 2) to simulate bioluminescence.
 */
public final class AbyssalTurfBlock extends Block {
    public AbyssalTurfBlock() {
        super(BlockBehaviour.Properties.of()
                .mapColor(MapColor.COLOR_CYAN)
                .strength(0.8F, 2.0F)
                .sound(SoundType.MOSS)
                .lightLevel(s -> 2)
                .requiresCorrectToolForDrops());
    }
}
