from pathlib import Path
import json
R=Path(__file__).resolve().parents[1];A=R/'src/main/resources/assets/interstice';D=R/'src/main/resources/data/interstice'
def write(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def box(fr,to,t):return {'from':fr,'to':to,'faces':{s:{'texture':t,'uv':[0,0,16,16]} for s in ['up','down','north','south','east','west']}}
write(A/'models/block/tether/rift_winch.json',{'parent':'minecraft:block/block','textures':{'particle':'interstice:block/garden/paleheart_planks','wood':'interstice:block/garden/paleheart_planks','metal':'interstice:block/minerals/riftsilver','line':'interstice:block/agriculture/plant_fiber'},'elements':[box([2,0,2],[14,3,14],'#wood'),box([3,3,4],[5,12,12],'#metal'),box([11,3,4],[13,12,12],'#metal'),box([5,5,5],[11,11,11],'#line'),box([4,6,3],[12,9,5],'#metal')]})
write(A/'blockstates/rift_winch.json',{'variants':{f'facing={face}':{'model':'interstice:block/tether/rift_winch','y':angle} for face,angle in [('north',0),('east',90),('south',180),('west',270)]}})
write(A/'models/item/rift_winch.json',{'parent':'interstice:block/tether/rift_winch'})
write(A/'models/item/tether_spool.json',{'parent':'minecraft:item/generated','textures':{'layer0':'interstice:block/agriculture/plant_fiber'}})
write(D/'loot_table/blocks/rift_winch.json',{'type':'minecraft:block','pools':[{'rolls':1,'conditions':[{'condition':'minecraft:survives_explosion'}],'entries':[{'type':'minecraft:item','name':'interstice:rift_winch'}]}]})
write(D/'recipe/rift_winch.json',{'type':'minecraft:crafting_shaped','category':'misc','pattern':['MLM','WSW','FPF'],'key':{'M':{'item':'interstice:riftsilver_mesh'},'L':{'item':'interstice:pure_vitriolite_lining'},'W':{'item':'interstice:world_stick'},'S':{'item':'interstice:riftsilver_ingot'},'F':{'item':'interstice:plant_fiber'},'P':{'tag':'interstice:world_planks'}},'result':{'id':'interstice:rift_winch','count':1}})
write(D/'recipe/tether_spool.json',{'type':'minecraft:crafting_shapeless','category':'equipment','ingredients':[{'item':'interstice:plant_fiber'}]*4+[{'item':'interstice:riftsilver_wire'}]*2+[{'item':'interstice:world_stick'}],'result':{'id':'interstice:tether_spool','count':1}})
for name in ['rift_winch','tether_spool']:
 write(D/f'advancement/recipes/tether/{name}.json',{'parent':'minecraft:recipes/root','criteria':{'native':{'trigger':'minecraft:inventory_changed','conditions':{'items':[{'items':'interstice:riftsilver_mesh'}]}}},'requirements':[['native']],'rewards':{'recipes':['interstice:'+name]}})
p=R/'src/main/resources/data/minecraft/tags/block/mineable/pickaxe.json';v=json.loads(p.read_text(encoding='utf-8'));v['values']=list(dict.fromkeys(v['values']+['interstice:rift_winch']));write(p,v)
write(R/'tools/tether_lang.json',{'block.interstice.rift_winch':['Рифтовая лебёдка','Rift winch'],'item.interstice.tether_spool':['Страховочная катушка','Tether spool'],'tooltip.interstice.tether_spool':['ПКМ по лебёдке: линия32бл. Присесть+ПКМ: отсоединить. Не является постоянной подвеской.','Use on winch:32-block line. Sneak-use: detach. Not a permanent suspension.'],'message.interstice.winch.attached':['Страховочная линия: %sбл.','Tether connected: %s blocks.'],'message.interstice.winch.broken':['Линия отсоединена: препятствие или потерянный узел.','Tether detached: obstruction or missing anchor.'],'message.interstice.winch.release_warning':['До освобождения линии1с: найдите опору!','Line releases in1s: find support!'],'message.interstice.winch.safety_release':['Линия освобождена: длительная неподвижная подвеска.','Tether released: prolonged unsupported suspension.']})
write(A/'provenance/tethers.json',{'operation':'Existing whole project textures in new model geometry; no new or copied bitmap','sources':['block/garden/paleheart_planks','block/minerals/riftsilver','block/agriculture/plant_fiber'],'rope':'References installed minecraft:textures/entity/lead_knot.png; no MojangPNG distributed','generator':'tools/generate_tether_resources.py'})
print('Winch/spool ready: models, recipes, loot, existing texture references; no newPNG')
